export const SPECIALITES = [
  'Médecine générale',
  'Cardiologie',
  'Dermatologie',
  'Endocrinologie',
  'Gastro-entérologie',
  'Gériatrie',
  'Gynécologie',
  'Hématologie',
  'Infectiologie',
  'Médecine du travail',
  'Médecine physique',
  'Néphrologie',
  'Neurologie',
  'Oncologie',
  'Ophtalmologie',
  'ORL',
  'Pédiatrie',
  'Pneumologie',
  'Psychiatrie',
  'Radiologie',
  'Rhumatologie',
  'Urologie',
  'Chirurgie générale',
  'Chirurgie orthopédique',
  'Anesthésie-réanimation',
  "Médecine d'urgence",
  'Autre',
]

export const MODES_EXERCICE = [
  'Libéral',
  'Salarié',
  'Mixte',
  'Hospitalier',
  'Remplaçant',
  'Étudiant',
]

/**
 * Correspondance code SM (Pro Santé Connect / DMP) → nom de spécialité.
 * Source : https://smt.esante.gouv.fr/fhir/ValueSet/JDV-J65-SubjectRole-DMP
 */
export const SM_SPECIALITES: Record<string, string> = {
  'SM01': 'Anatomie et Cytologie pathologiques',
  'SM02': 'Anesthésie-réanimation',
  'SM03': 'Biologie médicale',
  'SM04': 'Cardiologie et Maladies vasculaires',
  'SM05': 'Chirurgie générale',
  'SM06': 'Chirurgie maxillo-faciale',
  'SM07': 'Chirurgie maxillo-faciale et Stomatologie',
  'SM08': 'Chirurgie orthopédique et Traumatologie',
  'SM09': 'Chirurgie infantile',
  'SM10': 'Chirurgie plastique reconstructrice et esthétique',
  'SM11': 'Chirurgie thoracique et cardio-vasculaire',
  'SM12': 'Chirurgie urologique',
  'SM13': 'Chirurgie vasculaire',
  'SM14': 'Chirurgie viscérale et digestive',
  'SM15': 'Dermatologie et vénéréologie',
  'SM16': 'Endocrinologie et métabolisme',
  'SM17': 'Génétique médicale',
  'SM18': 'Gériatrie',
  'SM19': 'Gynécologie médicale',
  'SM20': 'Gynécologie-obstétrique',
  'SM21': 'Hématologie',
  'SM22': 'Hématologie, option Maladie du sang',
  'SM23': 'Hématologie, option Onco-hématologie',
  'SM24': 'Gastro-entérologie et Hépatologie',
  'SM25': 'Médecine du travail',
  'SM26': 'Médecin généraliste',
  'SM27': 'Médecine interne',
  'SM28': 'Médecine nucléaire',
  'SM29': 'Médecine physique et réadaptation',
  'SM30': 'Néphrologie',
  'SM31': 'Neuro-chirurgie',
  'SM32': 'Neurologie',
  'SM33': 'Neuro-psychiatrie',
  'SM34': 'ORL et Chirurgie cervico-faciale',
  'SM35': 'Oncologie, option Onco-hématologie',
  'SM36': 'Oncologie, option médicale',
  'SM37': 'Oncologie, option radiothérapie',
  'SM38': 'Ophtalmologie',
  'SM39': 'Oto-rhino-laryngologie',
  'SM40': 'Pédiatrie',
  'SM41': 'Pneumologie',
  'SM42': 'Psychiatrie',
  'SM43': 'Psychiatrie, option enfant et adolescent',
  'SM44': 'Radio-diagnostic',
  'SM45': 'Radio-thérapie',
  'SM46': 'Médecine intensive-réanimation',
  'SM47': 'Recherche médicale',
  'SM48': 'Rhumatologie',
  'SM49': 'Santé publique et Médecine sociale',
  'SM50': 'Stomatologie',
  'SM51': 'Gynéco-obstétrique et Gynéco-médicale, option Gynéco-obstétrique',
  'SM52': 'Gynéco-obstétrique et Gynéco-médicale, option Gynéco-médicale',
  'SM53': 'Médecin généraliste',
  'SM54': 'Médecin généraliste',
  'SM55': 'Radio-diagnostic et Radio-thérapie',
  'SM56': 'Chirurgie orale',
  'SM57': 'Allergologie',
  'SM58': 'Maladies infectieuses et tropicales',
  'SM59': "Médecine d'urgence",
  'SM60': 'Médecine légale et expertises médicales',
  'SM61': 'Médecine vasculaire',
  'SM62': 'Endocrinologie, diabétologie, nutrition',
  'SM63': 'Biologie médicale option biologie générale',
  'SM64': 'Biologie médicale option médecine moléculaire, génétique et pharmacologie',
  'SM65': 'Biologie médicale option hématologie et immunologie',
  'SM66': 'Biologie médicale option agents infectieux',
  'SM67': 'Biologie médicale option biologie de la reproduction',
  'SM68': 'Chirurgie maxillo-faciale (réforme 2017)',
  'SM69': 'Chirurgie pédiatrique option chirurgie viscérale pédiatrique',
  'SM70': 'Chirurgie pédiatrique option orthopédie pédiatrique',
  'SM71': 'Hématologie (réforme 2017)',
  'SM72': 'Médecine interne et immunologie clinique',
  'SM73': 'Médecine cardiovasculaire',
  'SM74': 'Radiologie et imagerie médicale',
  'SM75': 'Santé publique',
  'SM76': 'Anesthésie-réanimation option anesthésie-pédiatrique',
  'SM77': 'Chirurgie maxillo-faciale option orthodontie des dysmorphies maxillo-faciales',
  'SM78': 'Chirurgie viscérale et digestive option endoscopie chirurgicale',
  'SM79': 'Médecine cardiovasculaire option cardiologie interventionnelle',
  'SM80': "Médecine cardiovasculaire option imagerie cardio d'expert",
  'SM81': 'Médecine cardiovasculaire option rythmologie interventionnelle et stimulation cardiaque',
  'SM82': 'Médecine intensive-réanimation option réanimation pédiatrique',
  'SM83': 'Néphrologie option soins intensifs néphrologiques',
  'SM84': "Neurologie option traitement interventionnel de l'ischémie cérébrale aigüe",
  'SM85': 'Ophtalmologie option chirurgie ophtalmopédiatrique et strabologique',
  'SM86': 'ORL et chirurgie cervico-faciale option audiophonologie',
  'SM87': 'Pédiatrie option néonatologie',
  'SM88': 'Pédiatrie option neuropédiatrie',
  'SM89': 'Pédiatrie option pneumopédiatrie',
  'SM90': 'Pédiatrie option réanimation pédiatrique',
  'SM91': 'Pneumologie option soins intensifs respiratoires',
  'SM92': 'Psychiatrie option enfant et adolescent',
  'SM93': 'Psychiatrie option psychiatrie personne âgée',
  'SM94': 'Radiologie imagerie médicale option radiologie interventionnelle avancée',
  'SM95': 'Santé publique option administration de la santé',
}

/**
 * Résout un code de spécialité SM (ex: "SM 40", "SM40") en nom lisible.
 * Retourne la valeur originale si le code n'est pas trouvé.
 */
export function resolveSpecialite(value: string | null): string | null {
  if (!value) return null
  const normalized = value.replace(/\s+/g, '').toUpperCase()
  return SM_SPECIALITES[normalized] ?? value
}

export const AVATARS = Array.from({ length: 48 }, (_, i) => ({
  id: `avatar-${i + 1}`,
  url: `/images/portraits/avatar-${i + 1}.png`,
}))
